Revise validation/tests script to execute tests in parallel.

diff --git a/taxcalc/validation/tests b/taxcalc/validation/tests
--- a/taxcalc/validation/tests
+++ b/taxcalc/validation/tests
@@ -1,32 +1,34 @@
 #!/bin/bash
-# Executes current-law validation TESTS using Tax-Calculator SimpleTaxIO class
-# as follows:
-# (1) generating a random sample of tax filing units (INPUT),
-# (2) generating OUTPUT from INPUT using simtax.py, and
-# (3) generating tax-difference tabulations by comparing OUTPUT with
-#     output file generated by Internet-TAXSIM using the same INPUT.
+# Executes current-law validation TESTS by calling test bash script.
 # .... check number of command-line arguments
-if [[ "$#" -gt 0 ]]; then
-    echo "ERROR: no command-line arguments allowed"
+if [[ "$#" -gt 1 ]]; then
+    echo "ERROR: can specify at most one command-line argument"
+    echo "USAGE: ./tests [all]"
     exit 1
 fi
-# .... specify simtax.py options appropriate for validation tests
-OPTIONS="--taxsim2441"
-# .... execute validation tests
-clear
-echo "Current-law validation TESTS using the Tax-Calculator SimpleTaxIO class"
-echo "(the tests compare Tax-Calculator and Internet-TAXSIM results)"
-for LYY in a13 a14 b13 b14 c13 c14
-do
-    echo "`date` : $LYY"
-    L=${LYY:0:1}    
-    YY=${LYY:1:2}
-    tclsh make-in.tcl 20$YY $L > $LYY.in
-    python ../../simtax.py $OPTIONS $LYY.in
-    unzip -oq out-taxsim.zip $LYY.in.out-taxsim
-    tclsh taxdiffs.tcl $LYY.in.out-simtax $LYY.in.out-taxsim > $LYY.taxdiffs
-    git diff --name-status $LYY.taxdiffs
-    rm $LYY.in $LYY.in.out-simtax $LYY.in.out-taxsim
-done
-echo "`date`"
+# .... specify whether or not to execute all tests
+ALLTESTS=false
+if [[ "$#" -eq 1 ]]; then
+    if [[ "$1" == "all" ]]; then
+        ALLTESTS=true
+    else
+        echo "ERROR: optional command-line argument must be all"
+        echo "USAGE: ./tests [all]"
+        exit 1
+    fi
+fi
+# .... execute validation tests in parallel
+echo "STARTING WITH CURLAW TESTS : `date`"
+if [[ "$ALLTESTS" == true ]] ; then
+    ./test a13 &
+    ./test a14 &
+    wait
+    ./test b13 &
+    ./test b14 &
+    wait
+fi
+./test c13 &
+./test c14 &
+wait
+echo "FINISHED WITH CURLAW TESTS : `date`"
 exit 0
