Add save option (that skips rm command) to the validation/test script.
This feature makes it easier to use the "bash test ..." command when
debugging Tax-Calculator logic.

diff --git a/taxcalc/validation/test b/taxcalc/validation/test
--- a/taxcalc/validation/test
+++ b/taxcalc/validation/test
@@ -4,16 +4,29 @@
 # (3) generate tax-difference tabulations by comparing OUTPUT with output
 #     file generated by Internet-TAXSIM using the same INPUT and REFORM.
 # Check command-line arguments
-if [[ "$#" -ne 2 ]]; then
-    echo "ERROR: not exactly two command-line arguments"
-    echo "USAGE: bash test LYY REFORM"
-    echo "       where L is letter in [a,b,c] and YY is number in [13,14]"
-    echo "       and where REFORM is Internet-TAXSIM option (e.g., '50_1') or"
-    echo "       '.' for no reform (i.e., current-law policy)"
+if [[ "$#" -lt 2 || "$#" -gt 3 ]]; then
+    echo "ERROR: number of command-line arguments not in 2-to-3 range"
+    echo "USAGE: bash test LYY REFORM [save]"
+    echo "       WHERE L is a letter equal to 'a', 'b', or 'c' and"
+    echo "             YY is a number equal to '13' or '14';"
+    echo "       WHERE REFORM is Internet-TAXSIM option (e.g., '50_1') or"
+    echo "             '.' for no reform (i.e., current-law policy);"
+    echo "       WHERE the 'save' option skips the deletion of INPUT and"
+    echo "             OUTPUT files at the end of the test"
     exit 1
 fi
 LYY=$1
 REFORM=$2
+SAVE=false
+if [[ "$#" -eq 3 ]]; then
+    if [[ "$3" == "save" ]]; then
+        SAVE=true
+    else
+        echo "ERROR: optional third command-line argument must be 'save'"
+        echo "USAGE: bash test LYY REFORM [save]"
+        exit 1
+    fi
+fi
 # Generate specified INPUT file
 L=${LYY:0:1}    
 YY=${LYY:1:2}
@@ -37,5 +50,7 @@ tclsh taxdiffs.tcl $OVAR4 $LYY.in.out-simtax$SUFFIX \
 # Check for difference between actual .taxdiffs and expected .taxdiffs files
 git diff --name-status $LYY$SUFFIX.taxdiffs
 # Remove temporary files
-rm $LYY.in $LYY.in.out-simtax$SUFFIX $LYY.in.out-taxsim$SUFFIX
+if [[ "$SAVE" == false ]] ; then
+    rm $LYY.in $LYY.in.out-simtax$SUFFIX $LYY.in.out-taxsim$SUFFIX
+fi
 exit 0
